begin;
create table if not exists countries
(
	country_code char(2) not null
		constraint countries_pkey
			primary key,
	country_name varchar(50) not null
		constraint countries_country_name_key
			unique,
	continent varchar(20) not null
)
;
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('dz', 'Algeria', 'AFRICA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('ao', 'Angola', 'AFRICA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('bj', 'Benin', 'AFRICA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('bw', 'Botswana', 'AFRICA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('bf', 'Burkina Faso', 'AFRICA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('bi', 'Burundi', 'AFRICA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('cm', 'Cameroon', 'AFRICA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('cf', 'Central African Republic', 'AFRICA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('td', 'Chad', 'AFRICA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('km', 'Comoros', 'AFRICA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('cg', 'Congo Brazzaville', 'AFRICA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('cd', 'Congo Kinshasa', 'AFRICA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('ci', 'Cote d''Ivoire', 'AFRICA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('dj', 'Djibouti', 'AFRICA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('eg', 'Egypt', 'AFRICA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('gq', 'Equatorial Guinea', 'AFRICA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('er', 'Eritrea', 'AFRICA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('et', 'Ethiopia', 'AFRICA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('ga', 'Gabon', 'AFRICA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('gm', 'Gambia', 'AFRICA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('gh', 'Ghana', 'AFRICA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('gn', 'Guinea', 'AFRICA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('gw', 'Guinea-Bissau', 'AFRICA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('ke', 'Kenya', 'AFRICA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('ls', 'Lesotho', 'AFRICA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('lr', 'Liberia', 'AFRICA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('ly', 'Libya', 'AFRICA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('mg', 'Madagascar', 'AFRICA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('mw', 'Malawi', 'AFRICA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('ml', 'Mali', 'AFRICA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('mr', 'Mauritania', 'AFRICA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('mu', 'Mauritius', 'AFRICA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('ma', 'Morocco', 'AFRICA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('mz', 'Mozambique', 'AFRICA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('na', 'Namibia', 'AFRICA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('ne', 'Niger', 'AFRICA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('ng', 'Nigeria', 'AFRICA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('rw', 'Rwanda', 'AFRICA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('sn', 'Senegal', 'AFRICA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('sc', 'Seychelles', 'AFRICA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('sl', 'Sierra Leone', 'AFRICA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('so', 'Somalia', 'AFRICA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('za', 'South Africa', 'AFRICA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('ss', 'South Sudan', 'AFRICA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('sd', 'Sudan', 'AFRICA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('sz', 'Swaziland', 'AFRICA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('tz', 'Tanzania', 'AFRICA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('tg', 'Togo', 'AFRICA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('tn', 'Tunisia', 'AFRICA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('ug', 'Uganda', 'AFRICA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('zm', 'Zambia', 'AFRICA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('zw', 'Zimbabwe', 'AFRICA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('ar', 'Argentina', 'AMERICA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('bs', 'Bahamas', 'AMERICA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('bb', 'Barbados', 'AMERICA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('bz', 'Belize', 'AMERICA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('bm', 'Bermuda', 'AMERICA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('bo', 'Bolivia', 'AMERICA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('br', 'Brazil', 'AMERICA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('ca', 'Canada', 'AMERICA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('cl', 'Chile', 'AMERICA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('co', 'Colombia', 'AMERICA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('cr', 'Costa Rica', 'AMERICA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('cu', 'Cuba', 'AMERICA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('dm', 'Dominica', 'AMERICA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('do', 'Dominican Republic', 'AMERICA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('ec', 'Ecuador', 'AMERICA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('sv', 'El Salvador', 'AMERICA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('gd', 'Grenada', 'AMERICA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('gt', 'Guatemala', 'AMERICA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('gy', 'Guyana', 'AMERICA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('ht', 'Haiti', 'AMERICA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('hn', 'Honduras', 'AMERICA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('jm', 'Jamaica', 'AMERICA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('mx', 'Mexico', 'AMERICA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('ni', 'Nicaragua', 'AMERICA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('pa', 'Panama', 'AMERICA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('py', 'Paraguay', 'AMERICA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('pe', 'Peru', 'AMERICA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('pr', 'Puerto Rico', 'AMERICA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('sr', 'Suriname', 'AMERICA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('tt', 'Trinidad and Tobago', 'AMERICA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('us', 'United States', 'AMERICA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('uy', 'Uruguay', 'AMERICA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('ve', 'Venezuela', 'AMERICA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('af', 'Afghanistan', 'ASIA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('am', 'Armenia', 'ASIA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('az', 'Azerbaijan', 'ASIA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('bh', 'Bahrain', 'ASIA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('bd', 'Bangladesh', 'ASIA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('bt', 'Bhutan', 'ASIA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('bn', 'Brunei', 'ASIA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('kh', 'Cambodia', 'ASIA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('cn', 'China', 'ASIA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('ge', 'Georgia', 'ASIA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('hk', 'Hong Kong', 'ASIA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('in', 'India', 'ASIA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('id', 'Indonesia', 'ASIA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('ir', 'Iran', 'ASIA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('iq', 'Iraq', 'ASIA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('il', 'Israel', 'ASIA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('jp', 'Japan', 'ASIA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('jo', 'Jordan', 'ASIA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('kz', 'Kazakhstan', 'ASIA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('kw', 'Kuwait', 'ASIA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('kg', 'Kyrgyzstan', 'ASIA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('la', 'Laos', 'ASIA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('lb', 'Lebanon', 'ASIA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('my', 'Malaysia', 'ASIA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('mv', 'Maldives', 'ASIA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('mn', 'Mongolia', 'ASIA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('mm', 'Myanmar', 'ASIA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('np', 'Nepal', 'ASIA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('kp', 'North Korea', 'ASIA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('om', 'Oman', 'ASIA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('pk', 'Pakistan', 'ASIA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('ph', 'Philippines', 'ASIA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('qa', 'Qatar', 'ASIA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('sa', 'Saudi Arabia', 'ASIA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('sg', 'Singapore', 'ASIA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('kr', 'South Korea', 'ASIA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('lk', 'Sri Lanka', 'ASIA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('sy', 'Syria', 'ASIA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('tw', 'Taiwan', 'ASIA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('tj', 'Tajikistan', 'ASIA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('th', 'Thailand', 'ASIA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('tl', 'Timor-Leste', 'ASIA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('tr', 'Turkey', 'ASIA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('tm', 'Turkmenistan', 'ASIA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('ae', 'United Arab Emirates', 'ASIA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('uz', 'Uzbekistan', 'ASIA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('vn', 'Vietnam', 'ASIA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('ye', 'Yemen', 'ASIA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('al', 'Albania', 'EUROPE');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('at', 'Austria', 'EUROPE');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('by', 'Belarus', 'EUROPE');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('be', 'Belgium', 'EUROPE');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('ba', 'Bosnia and Herzegovina', 'EUROPE');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('bg', 'Bulgaria', 'EUROPE');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('hr', 'Croatia', 'EUROPE');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('cy', 'Cyprus', 'EUROPE');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('cz', 'Czech Republic', 'EUROPE');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('dk', 'Denmark', 'EUROPE');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('ee', 'Estonia', 'EUROPE');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('fi', 'Finland', 'EUROPE');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('fr', 'France', 'EUROPE');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('de', 'Germany', 'EUROPE');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('gr', 'Greece', 'EUROPE');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('hu', 'Hungary', 'EUROPE');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('is', 'Iceland', 'EUROPE');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('ie', 'Ireland', 'EUROPE');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('it', 'Italy', 'EUROPE');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('lv', 'Latvia', 'EUROPE');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('lt', 'Lithuania', 'EUROPE');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('lu', 'Luxembourg', 'EUROPE');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('mk', 'Macedonia', 'EUROPE');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('mt', 'Malta', 'EUROPE');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('md', 'Moldova', 'EUROPE');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('me', 'Montenegro', 'EUROPE');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('nl', 'Netherlands', 'EUROPE');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('no', 'Norway', 'EUROPE');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('pl', 'Poland', 'EUROPE');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('pt', 'Portugal', 'EUROPE');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('ro', 'Romania', 'EUROPE');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('ru', 'Russia', 'EUROPE');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('rs', 'Serbia', 'EUROPE');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('sk', 'Slovakia', 'EUROPE');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('si', 'Slovenia', 'EUROPE');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('sp', 'Spain', 'EUROPE');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('se', 'Sweden', 'EUROPE');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('ch', 'Switzerland', 'EUROPE');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('ua', 'Ukraine', 'EUROPE');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('gb', 'United Kingdom', 'EUROPE');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('au', 'Australia', 'OCEANIA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('ck', 'Cook Islands', 'OCEANIA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('fj', 'Fiji', 'OCEANIA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('fm', 'Micronesia', 'OCEANIA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('nz', 'New Zealand', 'OCEANIA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('pg', 'Papua New Guinea', 'OCEANIA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('ws', 'Samoa', 'OCEANIA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('sb', 'Solomon Islands', 'OCEANIA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('tk', 'Tokelau', 'OCEANIA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('to', 'Tonga', 'OCEANIA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('tv', 'Tuvalu', 'OCEANIA');
INSERT INTO public.countries (country_code, country_name, continent) VALUES ('vu', 'Vanuatu', 'OCEANIA');
commit;
