all:
	pdflatex Assignment/assignment1.tex
	pdflatex Assignment/assignment2.tex
	pdflatex Assignment/assignment3.tex
	pdflatex Assignment/assignment4.tex
	pdflatex Assignment/assignment5.tex
	pdflatex Assignment/assignment6.tex
	mv *.pdf Assignment/submit

clean:
	rm -f *.bbl *.blg *.aux *.end *.fls *.log *.out *.fdb_latexmk *.synctex.gz

.PHONY: clean all